### ISSUE TITLE
Create `businesses` table in DB

### ISSUE THREAD

**Issue by jamiecoe** [FACN7/wajjbat-backend#9]

**Comment by Karyum** [comment]
| id | name | primaryImage | lat | lng | type | phone | address | email | parking | freeWifi | smokingArea | description | cuisine |
|----|------|--------------|-----|-----|------|-------|---------|-------|---------|----------|-------------|-------------|---------|
|    |      |              |     |     |      |       |         |       |         |          |             |             |         |
|    |      |              |     |     |      |       |         |       |         |          |             |             |         |
|    |      |              |     |     |      |       |         |       |         |          |             |             |         |
